
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Form handling
[build.processing.html]
  pretty_urls = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://*.netlify.app https://*.contentful.com https://*.googleapis.com https://*.gstatic.com; script-src 'self' 'unsafe-inline' https://*.netlify.app https://*.googleapis.com https://*.gstatic.com; style-src 'self' 'unsafe-inline' https://*.netlify.app https://*.googleapis.com https://*.gstatic.com; img-src 'self' data: https://*.netlify.app https://images.unsplash.com https://*.ctfassets.net https://images.ctfassets.net https://*.googleapis.com https://*.gstatic.com; font-src 'self' https://*.netlify.app https://*.googleapis.com https://*.gstatic.com; connect-src 'self' https://*.netlify.app https://*.contentful.com https://*.googleapis.com https://*.gstatic.com; frame-src 'self' https://*.google.com https://*.googleapis.com"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 
