[build]
  command = "npm ci && npm run build:prod"
  publish = "dist"
  environment = { NODE_VERSION = "18", NPM_VERSION = "10.8.2", NODE_ENV = "production" }

[build.processing]
  skip_processing = false
  html = { pretty_urls = true }
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  images = { compress = true }

[headers]
  for = "/*"
    [[headers.values]]
      key = "Content-Security-Policy"
      value = """
        default-src 'self';
        script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.netlify.app https://*.googleapis.com https://*.gstatic.com;
        style-src 'self' 'unsafe-inline' https://*.netlify.app https://*.googleapis.com https://*.gstatic.com;
        img-src 'self' data: https://*.netlify.app https://images.unsplash.com https://*.ctfassets.net https://images.ctfassets.net https://*.googleapis.com https://*.gstatic.com;
        font-src 'self' https://*.netlify.app https://*.googleapis.com https://*.gstatic.com;
        connect-src 'self' https://*.netlify.app https://*.contentful.com https://*.googleapis.com https://*.gstatic.com;
        frame-src 'self' https://*.google.com https://*.googleapis.com;
        object-src 'none';
        base-uri 'self';
        form-action 'self';
        frame-ancestors 'none';
        upgrade-insecure-requests;
      """
    [[headers.values]]
      key = "Permissions-Policy"
      value = "camera=(), microphone=(), geolocation=()"
    [[headers.values]]
      key = "Referrer-Policy"
      value = "strict-origin-when-cross-origin"
    [[headers.values]]
      key = "Strict-Transport-Security"
      value = "max-age=31536000; includeSubDomains"
    [[headers.values]]
      key = "X-Content-Type-Options"
      value = "nosniff"
    [[headers.values]]
      key = "X-Frame-Options"
      value = "DENY"
    [[headers.values]]
      key = "X-XSS-Protection"
      value = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173 
