[build]
  command = "npm install && npm run build:prod"
  publish = "dist"
  environment = { NODE_VERSION = "18", NPM_VERSION = "10.8.2", NODE_ENV = "production" }

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com https://*.supabase.co;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://*.netlify.app https://*.netlify.com https://*.supabase.co https://*.contentful.com;
      frame-src 'self' https://*.supabase.co;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://*.supabase.co;
      frame-ancestors 'none';
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173